#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Demandante;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Demandante/_DatosDemandante.cshtml")]
    public partial class _Views_Demandante__DatosDemandante_cshtml : System.Web.Mvc.WebViewPage<Core.Demandante.DemandanteModel>
    {
        public _Views_Demandante__DatosDemandante_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Datos de demandante:</h4><br />\r\n<div");

WriteLiteral(" data-ng-init=\"dataDemModel = ");

            
            #line 5 "..\..\Views\Demandante\_DatosDemandante.cshtml"
                             Write(Json.Encode(Model));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    \r\n    <div");

WriteLiteral(" id=\"misdatos\"");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(">\r\n        <br />\r\n        <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(" style=\"border-color: #428bca;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading clearfix\"");

WriteLiteral(" style=\"background-color:#428bca\"");

WriteLiteral(">\r\n                <b");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Datos de usuario:</b>\r\n                <button");

WriteLiteral(" class=\"btn btn-info pull-right\"");

WriteLiteral(" style=\"padding-top:0\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalEditarUsuario(dataDemModel)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-pencil\"");

WriteLiteral(" style=\"text-align:center; vertical-align:middle\"");

WriteLiteral("></i></button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(" style=\"padding-top:0; padding-bottom:0\"");

WriteLiteral(">\r\n                <ul");

WriteLiteral(" class=\"list-group row\"");

WriteLiteral(" style=\"margin-bottom:0;\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Usuario:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Usuario}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Nombre:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Nombre}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Primer apellido:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Apellido1}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Segundo apellido:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Apellido2}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Tipo de usuario:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" ng-if=\"dataDemModel.TipoUsuario == 0\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Empleador</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" ng-if=\"dataDemModel.TipoUsuario == 1\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Demandante</li>\r\n                </ul>\r\n            </div>\r\n        </div>\r\n\r\n  " +
"      <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(" style=\"border-color: #428bca;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"panel-heading clearfix\"");

WriteLiteral(" style=\"background-color:#428bca\"");

WriteLiteral(">\r\n                <b");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Datos de demandante:</b>\r\n                <button");

WriteLiteral(" class=\"btn btn-info pull-right\"");

WriteLiteral(" style=\"padding-top:0\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalEditarDemandante(dataDemModel)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-pencil\"");

WriteLiteral(" style=\"text-align:center; vertical-align:middle\"");

WriteLiteral("></i></button>\r\n            </div>\r\n            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(" style=\"padding-top:0; padding-bottom:0\"");

WriteLiteral(">\r\n\r\n                <ul");

WriteLiteral(" class=\"list-group row\"");

WriteLiteral(" style=\"margin-bottom:0\"");

WriteLiteral(">\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Foto de perfil:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"min-height:45px;\"");

WriteLiteral("><img");

WriteLiteral(" data-ng-src=\"data:image/jpg;base64,{{dataDemModel.ImagenB64}}\"");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" /></li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Edad:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Edad}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Teléfono:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Telefono}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Email:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Email}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Perfil de Linkedin:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.PerfilLinkedin}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Nivel de estudios:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.NivelEstudiosNombre}}</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Experiencia laboral:</li>\r\n                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.ExperienciaLaboral}}</li>\r\n                </ul>\r\n            </d" +
"iv>\r\n        </div> <!-- cierre panel -->\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
