#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Demandante;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Demandante/_OfertasDisponibles.cshtml")]
    public partial class _Views_Demandante__OfertasDisponibles_cshtml : System.Web.Mvc.WebViewPage<List<Core.Empleador.OfertaEmpleo>>
    {
        public _Views_Demandante__OfertasDisponibles_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Datos de oferta:</h4><br />\r\n<div");

WriteLiteral(" data-ng-init=\"listOfertasDisponibles = ");

            
            #line 5 "..\..\Views\Demandante\_OfertasDisponibles.cshtml"
                                       Write(Json.Encode(Model));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" id=\"ofertasDisponibles\"");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(">\r\n        <div");

WriteLiteral(" class=\"tab-content well well-sm\"");

WriteLiteral(" style=\"background-color:white; padding:0\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"padding:0\"");

WriteLiteral(">\r\n                <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                    <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n                        <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Título</th>\r\n                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Num. Vacantes</th>\r\n                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Sueldo</th>\r\n                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Fecha de creación</th>\r\n                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Fecha de finalización</th>\r\n                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">&equiv;</th>\r\n                        </tr>\r\n                    </thead>\r\n     " +
"               <tbody>\r\n                        <tr");

WriteLiteral(" ng-repeat=\"x in listOfertasDisponibles\"");

WriteLiteral(">\r\n                            <td");

WriteLiteral(" style=\"vertical-align:middle; margin-left:10px !important\"");

WriteLiteral(">{{x.Titulo}}</td>\r\n                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NumeroVacantes}}</td>\r\n                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Sueldo}}</td>\r\n                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaLanzamientoString}}</td>\r\n                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaFinString}}</td>\r\n                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalVerOfertaDisponible(x)\"");

WriteLiteral(">Ver detalles</button></td>\r\n                        </tr>\r\n                    <" +
"/tbody>\r\n                </table>\r\n            </div> <!-- cierre table -->\r\n   " +
"     </div>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
