#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Demandante;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Demandante/InicialDemandante.cshtml")]
    public partial class _Views_Demandante_InicialDemandante_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Demandante_InicialDemandante_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<!-- Scripts-->\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_es" +
"-es.min.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 372), Tuple.Create("\"", 419)
, Tuple.Create(Tuple.Create("", 378), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 378), false)
, Tuple.Create(Tuple.Create(" ", 387), Tuple.Create("propios/demandanteController.js", 388), true)
);

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" ng-app=\"app\"");

WriteLiteral(">\r\n\r\n    <div");

WriteLiteral(" ng-controller=\"DemandanteController\"");

WriteLiteral(" data-ng-init=\"ObtenerDatosDemandanteModel(");

WriteLiteral(")\"");

WriteLiteral(" class=\"demo\"");

WriteLiteral(" style=\"width:auto\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"titulo\"");

WriteLiteral(">\r\n                <br><br><br>\r\n                <h3>Hola <span");

WriteLiteral(" style=\"color:#b94a48\"");

WriteLiteral("><b>{{dataDemModel.Usuario}}</b></span> esta es tu página de <b>demandante</b>.</" +
"h3><br><br>  \r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(">\r\n                    <ul");

WriteLiteral(" class=\"nav nav-pills nav-justified well well-sm\"");

WriteLiteral(">\r\n                        <li");

WriteLiteral(" class=\"active\"");

WriteLiteral(" style=\"\"");

WriteLiteral("><a");

WriteLiteral(" data-toggle=\"pill\"");

WriteLiteral(" href=\"#misdatos\"");

WriteLiteral(">Mis datos</a></li>\r\n                        <li><a");

WriteLiteral(" data-toggle=\"pill\"");

WriteLiteral(" href=\"#ofertasDisponibles\"");

WriteLiteral(">Ofertas disponibles</a></li>\r\n                        <li><a");

WriteLiteral(" data-toggle=\"pill\"");

WriteLiteral(" href=\"#misOfertasInscritas\"");

WriteLiteral(">Mis ofertas inscritas</a></li>\r\n                    </ul>\r\n                </div" +
">\r\n\r\n\r\n                <div");

WriteLiteral(" class=\"tab-content well well-sm\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" id=\"misdatos\"");

WriteLiteral(" class=\"tab-pane fade in active\"");

WriteLiteral(">\r\n                        <br />\r\n                        <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(" style=\"border-color: #428bca;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(" style=\"background-color:#428bca\"");

WriteLiteral("><b");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Datos de usuario:</b></div>\r\n                            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(" style=\"padding-top:0; padding-bottom:0\"");

WriteLiteral(">\r\n                                <ul");

WriteLiteral(" class=\"list-group row\"");

WriteLiteral(" style=\"margin-bottom:0;\"");

WriteLiteral(">\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Usuario:</li>\r\n                                    ");

WriteLiteral("\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Usuario}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Nombre:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Nombre}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Primer apellido:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Apellido1}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Segundo apellido:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Apellido2}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Tipo de usuario:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" ng-if=\"dataDemModel.TipoUsuario == 0\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Empleador</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" ng-if=\"dataDemModel.TipoUsuario == 1\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Demandante</li>\r\n                                    ");

WriteLiteral("\r\n\r\n                                    \r\n                                </ul>\r\n" +
"                            </div>\r\n                        </div>\r\n\r\n          " +
"              <div");

WriteLiteral(" class=\"panel\"");

WriteLiteral(" style=\"border-color: #428bca;\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"panel-heading\"");

WriteLiteral(" style=\"background-color:#428bca\"");

WriteLiteral("><b");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Datos de demandante:</b></div>\r\n                            <div");

WriteLiteral(" class=\"panel-body\"");

WriteLiteral(" style=\"padding-top:0; padding-bottom:0\"");

WriteLiteral(">\r\n\r\n                                <ul");

WriteLiteral(" class=\"list-group row\"");

WriteLiteral(" style=\"margin-bottom:0\"");

WriteLiteral(">\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Foto de perfil:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"min-height:45px;\"");

WriteLiteral("><img");

WriteLiteral(" data-ng-src=\"data:image/jpg;base64,{{dataDemModel.ImagenB64}}\"");

WriteLiteral(" class=\"img-responsive\"");

WriteLiteral(" /></li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Edad:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Edad}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Teléfono:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Telefono}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Email:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.Email}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Perfil de Linkedin:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.PerfilLinkedin}}</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Nivel de estudios:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.NivelEstudiosNombre}}</li>\r\n                                    <" +
"li");

WriteLiteral(" class=\"list-group-item col-xs-4\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">Experiencia laboral:</li>\r\n                                    <li");

WriteLiteral(" class=\"list-group-item col-xs-8\"");

WriteLiteral(" style=\"height:45px;\"");

WriteLiteral(">{{dataDemModel.ExperienciaLaboral}}</li>\r\n                                </ul>\r" +
"\n                            </div>\r\n                        </div> <!-- cierre " +
"panel -->\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" id=\"ofertasDisponibles\"");

WriteLiteral(" class=\"tab-pane fade\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-content well well-sm\"");

WriteLiteral(" style=\"background-color:white; padding:0\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"padding:0\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n                                        <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Título</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Num. Vacantes</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Sueldo</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Fecha de creación</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Fecha de finalización</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">&equiv;</th>\r\n                                        </tr>\r\n                   " +
"                 </thead>\r\n                                    <tbody>\r\n        " +
"                                <tr");

WriteLiteral(" ng-repeat=\"x in listOfertasDisponibles\"");

WriteLiteral(">\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle; margin-left:10px !important\"");

WriteLiteral(">{{x.Titulo}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NumeroVacantes}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Sueldo}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaLanzamientoString}}</td>\r\n                                            <" +
"td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaFinString}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalVerOfertaDisponible(x)\"");

WriteLiteral(@">Ver detalles</button></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div> <!-- cierre table -->
                        </div>
                    </div>

                    <div");

WriteLiteral(" id=\"misOfertasInscritas\"");

WriteLiteral(" class=\"tab-pane fade \"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"tab-content well well-sm\"");

WriteLiteral(" style=\"background-color:white; padding:0\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"container\"");

WriteLiteral(" style=\"padding:0\"");

WriteLiteral(">\r\n                                <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n                                        <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Título</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Num. Vacantes</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Sueldo</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Fecha de creación</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Fecha de finalización</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Estado inscripción</th>\r\n                                            <th");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">&equiv;</th>\r\n                                        </tr>\r\n                   " +
"                 </thead>\r\n                                    <tbody>\r\n        " +
"                                <tr");

WriteLiteral(" ng-repeat=\"x in listOfertasInscritas\"");

WriteLiteral(">\r\n                                            <td");

WriteLiteral(" class=\"sc\"");

WriteLiteral(" style=\"vertical-align:middle; margin-left:10px !important\"");

WriteLiteral(">{{x.Titulo}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NumeroVacantes}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Sueldo}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaLanzamientoString}}</td>\r\n                                            <" +
"td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaFinString}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Nombre}}</td>\r\n                                            <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalVerOfertaInscrita(x)\"");

WriteLiteral(@">Ver detalles</button></td>
                                        </tr>
                                    </tbody>
                                </table>
                            </div> <!-- cierre table -->
                        </div>
                    </div>
                </div>
            </div><!-- div class row-->





            <!--  MODAL VER DETALLE OFERTA DISPONIBLE  ###############################  -->
            <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalVerOfertaDisponible\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color:#f0ad4e; padding-bottom:0\"");

WriteLiteral(">\r\n                            <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Detalles de la oferta de empleo:</h4>\r\n                        </div>\r\n\r\n       " +
"                 <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <h3><b>{{ofertaDetalleModal.Titulo}}</" +
"b></h3>\r\n                                        <p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Descripcion}}</p>\r\n                                    </di" +
"v>\r\n                                </div>\r\n                            </div>\r\n" +
"                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <br />\r\n                              " +
"          <b>Observaciones:</b><br />\r\n                                        <" +
"p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Observaciones}}</p>\r\n                                    </" +
"div>\r\n                                </div>\r\n                            </div>" +
"\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(">\r\n                                <hr />\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Disponibilidad:</p>\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><span><b>{{ofertaDetalleModal.FechaLanzamientoString}}</b></span> - <span><b>{{o" +
"fertaDetalleModal.FechaFinString}}</b></span></p><br />\r\n                       " +
"         </div>\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">{{ofertaDetalleModal.NumeroVacantes}}   </b>   <i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("></i><br />\r\n                                </div>\r\n                            " +
"    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    ");

WriteLiteral("<b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">  {{ofertaDetalleModal.Sueldo}} €</b><br />\r\n                                </d" +
"iv>\r\n                            </div>\r\n                            <hr /><br /" +
">\r\n\r\n                            <div");

WriteLiteral(" class=\"row well well-lg\"");

WriteLiteral(" style=\"margin:auto; background-color:#fdf5ee\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><b>¿Te interesa la oferta?</b></p>\r\n                                        <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Rellena los siguientes datos e inscríbete</p><br />\r\n                           " +
"             <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.Notas\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"notas\"");

WriteLiteral(" id=\"notas\"");

WriteLiteral(" placeholder=\"Añade algún comentario...\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" /><br />\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.CV\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"cv\"");

WriteLiteral(" id=\"cv\"");

WriteLiteral(" placeholder=\"Introduce tu currículum...\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" /><br />\r\n\r\n                                        <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-warning btn-block\"");

WriteLiteral(" value=\"Inscribirse\"");

WriteLiteral(" id=\"btnInscribir\"");

WriteLiteral(" ng-click=\"InscribirDemandante()\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(" />\r\n                                    </div>\r\n                                " +
"</div>\r\n                            </div>\r\n                        </div>\r\n\r\n  " +
"                      <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(@">Atrás</button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- ################################ -->



            <!--  MODAL VER DETALLE OFERTA INSCRITA  ###############################  -->
            <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalVerOfertaInscrita\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                        <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color:#f0ad4e; padding-bottom:0\"");

WriteLiteral(">\r\n                            <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Detalles de la oferta de empleo:</h4>\r\n                        </div>\r\n\r\n       " +
"                 <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <h3><b>{{ofertaDetalleModal.Titulo}}</" +
"b></h3>\r\n                                        <p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Descripcion}}</p>\r\n                                    </di" +
"v>\r\n                                </div>\r\n                            </div>\r\n" +
"                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <br />\r\n                              " +
"          <b>Observaciones:</b><br />\r\n                                        <" +
"p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Observaciones}}</p>\r\n                                    </" +
"div>\r\n                                </div>\r\n                            </div>" +
"\r\n                            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(">\r\n                                <hr />\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Disponibilidad:</p>\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><span><b>{{ofertaDetalleModal.FechaLanzamientoString}}</b></span> - <span><b>{{o" +
"fertaDetalleModal.FechaFinString}}</b></span></p><br />\r\n                       " +
"         </div>\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">{{ofertaDetalleModal.NumeroVacantes}}   </b>   <i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("></i><br />\r\n                                </div>\r\n                            " +
"    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                    <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">  {{ofertaDetalleModal.Sueldo}} €</b><br />\r\n                                </d" +
"iv>\r\n                            </div>\r\n                            <hr /><br /" +
">\r\n\r\n                            <div");

WriteLiteral(" class=\"row well well-lg\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                        <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><b>¡Ya estás inscrito en esta oferta de empleo!</b></p>\r\n                       " +
"                 <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Estos son tus datos de la inscripción:</p><br />\r\n                              " +
"          <label");

WriteLiteral(" for=\"notas\"");

WriteLiteral(">Notas:</label>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.Notas\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"notas\"");

WriteLiteral(" id=\"notas\"");

WriteLiteral(" placeholder=\"{{ofertaDetalleModal.Notas}}\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" disabled/><br />\r\n                                        <label");

WriteLiteral(" for=\"cv\"");

WriteLiteral(">Currículum vitae:</label>\r\n                                        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.CV\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"cv\"");

WriteLiteral(" id=\"cv\"");

WriteLiteral(" placeholder=\"{{ofertaDetalleModal.CV}}\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" disabled/><br /><br />\r\n                                        <label");

WriteLiteral(" for=\"cv\"");

WriteLiteral(">Estado de la inscripción:</label>\r\n                                        <inpu" +
"t");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.Nombre\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"cv\"");

WriteLiteral(" id=\"cv\"");

WriteLiteral(" placeholder=\"{{ofertaDetalleModal.Nombre}}\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" disabled /><br />\r\n\r\n                                        <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn btn-block\"");

WriteLiteral(" value=\"Desinscribirse\"");

WriteLiteral(" id=\"btnDesinscribir\"");

WriteLiteral(" ");

WriteLiteral(" style=\"margin:auto; background-color: dimgray; color: white;\" />\r\n              " +
"                      </div>\r\n                                </div>\r\n          " +
"                  </div>\r\n                        </div>\r\n\r\n                    " +
"    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                            <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Atrás</button>\r\n                        </div>\r\n                    </div>\r\n    " +
"            </div>\r\n            </div>\r\n            <!-- #######################" +
"######### -->\r\n\r\n\r\n\r\n        </div> \r\n    </form>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
