#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Demandante;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Demandante/InicialDemandante.cshtml")]
    public partial class _Views_Demandante_InicialDemandante_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Demandante_InicialDemandante_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n<!-- Scripts-->\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_es" +
"-es.min.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 372), Tuple.Create("\"", 419)
, Tuple.Create(Tuple.Create("", 378), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 378), false)
, Tuple.Create(Tuple.Create(" ", 387), Tuple.Create("propios/demandanteController.js", 388), true)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 439), Tuple.Create("\"", 479)
, Tuple.Create(Tuple.Create("", 445), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 445), false)
, Tuple.Create(Tuple.Create(" ", 454), Tuple.Create("propios/scriptCompile.js", 455), true)
);

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" ng-app=\"app\"");

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\'", 522), Tuple.Create("\'", 563)
, Tuple.Create(Tuple.Create("", 528), Tuple.Create<System.Object, System.Int32>(Href("~/Imagenes/pexels-photo-884454.jpeg")
, 528), false)
);

WriteLiteral(" style=\'position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;opacity:0.2" +
"5\'");

WriteLiteral(">\r\n\r\n\r\n    <div");

WriteLiteral(" ng-controller=\"DemandanteController\"");

WriteLiteral(" ng-init=\"GetDatos()\"");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"width:auto\"");

WriteLiteral(">\r\n\r\n        <div");

WriteLiteral(" class=\"titulo\"");

WriteLiteral(">\r\n            <br><br><br>\r\n            <h3>Hola <span");

WriteLiteral(" style=\"color:#b94a48\"");

WriteLiteral("><b>{{dataDemModel.Usuario}}</b></span> esta es tu página de <b>demandante</b>.</" +
"h3><br><br>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(" style=\"height:690px\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"btn-group-vertical container\"");

WriteLiteral(">\r\n                <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"padding-right:80px; text-align:left; border-radius:0; opacity:0.9\"");

WriteLiteral(" ng-click=\"GetDatos()\"");

WriteLiteral("> Mis datos</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"text-align:left; border-radius:0; opacity:0.9\"");

WriteLiteral(" ng-click=\"GetOfertasDisponibles()\"");

WriteLiteral("> Ofertas disponibles</button>\r\n                <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"text-align:left; border-radius:0; opacity:0.9\"");

WriteLiteral("> Ofertas inscritas</button>\r\n            </div>\r\n        </div>\r\n\r\n        <div");

WriteLiteral(" class=\"col-sm-10 well well-lg\"");

WriteLiteral(" style=\"border-radius: 0;\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"MisDatos\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"OfertasDisponibles\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"OfertasInscritas\"");

WriteLiteral("></div>\r\n        </div>\r\n\r\n        ");

WriteLiteral("\r\n\r\n\r\n\r\n        <!--  MODAL VER DETALLE OFERTA DISPONIBLE  ######################" +
"#########  -->\r\n        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalVerOfertaDisponible\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color:#f0ad4e; padding-bottom:0\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Detalles de la oferta de empleo:</h4>\r\n                    </div>\r\n\r\n           " +
"         <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <h3><b>{{ofertaDetalleModal.Titulo}}</b></" +
"h3>\r\n                                    <p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Descripcion}}</p>\r\n                                </div>\r\n" +
"                            </div>\r\n                        </div>\r\n            " +
"            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <br />\r\n                                  " +
"  <b>Observaciones:</b><br />\r\n                                    <p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Observaciones}}</p>\r\n                                </div>" +
"\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(">\r\n                            <hr />\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Disponibilidad:</p>\r\n                                <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><span><b>{{ofertaDetalleModal.FechaLanzamientoString}}</b></span> - <span><b>{{o" +
"fertaDetalleModal.FechaFinString}}</b></span></p><br />\r\n                       " +
"     </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">{{ofertaDetalleModal.NumeroVacantes}}   </b>   <i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("></i><br />\r\n                            </div>\r\n                            <div" +
"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">  {{ofertaDetalleModal.Sueldo}} €</b><br />\r\n                            </div>\r" +
"\n                        </div>\r\n                        <hr /><br />\r\n\r\n       " +
"                 <div");

WriteLiteral(" class=\"row well well-lg\"");

WriteLiteral(" style=\"margin:auto; background-color:#fdf5ee\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><b>¿Te interesa la oferta?</b></p>\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Rellena los siguientes datos e inscríbete</p><br />\r\n                           " +
"         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.Notas\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"notas\"");

WriteLiteral(" id=\"notas\"");

WriteLiteral(" placeholder=\"Añade algún comentario...\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" /><br />\r\n                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.CV\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"cv\"");

WriteLiteral(" id=\"cv\"");

WriteLiteral(" placeholder=\"Introduce tu currículum...\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" /><br />\r\n\r\n                                    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-warning btn-block\"");

WriteLiteral(" value=\"Inscribirse\"");

WriteLiteral(" id=\"btnInscribir\"");

WriteLiteral(" ng-click=\"InscribirDemandante()\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(" />\r\n                                </div>\r\n                            </div>\r\n" +
"                        </div>\r\n                    </div>\r\n\r\n                  " +
"  <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Atrás</button>\r\n                    </div>\r\n                </div>\r\n            " +
"</div>\r\n        </div>\r\n        <!-- ################################ -->\r\n     " +
"   <!--  MODAL VER DETALLE OFERTA INSCRITA  ###############################  -->" +
"\r\n        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalVerOfertaInscrita\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color:#f0ad4e; padding-bottom:0\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Detalles de la oferta de empleo:</h4>\r\n                    </div>\r\n\r\n           " +
"         <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <h3><b>{{ofertaDetalleModal.Titulo}}</b></" +
"h3>\r\n                                    <p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Descripcion}}</p>\r\n                                </div>\r\n" +
"                            </div>\r\n                        </div>\r\n            " +
"            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <br />\r\n                                  " +
"  <b>Observaciones:</b><br />\r\n                                    <p");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">{{ofertaDetalleModal.Observaciones}}</p>\r\n                                </div>" +
"\r\n                            </div>\r\n                        </div>\r\n          " +
"              <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(">\r\n                            <hr />\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Disponibilidad:</p>\r\n                                <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><span><b>{{ofertaDetalleModal.FechaLanzamientoString}}</b></span> - <span><b>{{o" +
"fertaDetalleModal.FechaFinString}}</b></span></p><br />\r\n                       " +
"     </div>\r\n                            <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">{{ofertaDetalleModal.NumeroVacantes}}   </b>   <i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("></i><br />\r\n                            </div>\r\n                            <div" +
"");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n                                <b");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">  {{ofertaDetalleModal.Sueldo}} €</b><br />\r\n                            </div>\r" +
"\n                        </div>\r\n                        <hr /><br />\r\n\r\n       " +
"                 <div");

WriteLiteral(" class=\"row well well-lg\"");

WriteLiteral(" style=\"margin:auto\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral("><b>¡Ya estás inscrito en esta oferta de empleo!</b></p>\r\n                       " +
"             <p");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">Estos son tus datos de la inscripción:</p><br />\r\n                              " +
"      <label");

WriteLiteral(" for=\"notas\"");

WriteLiteral(">Notas:</label>\r\n                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.Notas\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"notas\"");

WriteLiteral(" id=\"notas\"");

WriteLiteral(" placeholder=\"{{ofertaDetalleModal.Notas}}\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" disabled /><br />\r\n                                    <label");

WriteLiteral(" for=\"cv\"");

WriteLiteral(">Currículum vitae:</label>\r\n                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.CV\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"cv\"");

WriteLiteral(" id=\"cv\"");

WriteLiteral(" placeholder=\"{{ofertaDetalleModal.CV}}\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" disabled /><br /><br />\r\n                                    <label");

WriteLiteral(" for=\"cv\"");

WriteLiteral(">Estado de la inscripción:</label>\r\n                                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"inscripcion.Nombre\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"cv\"");

WriteLiteral(" id=\"cv\"");

WriteLiteral(" placeholder=\"{{ofertaDetalleModal.Nombre}}\"");

WriteLiteral(" style=\"max-width:500px;\"");

WriteLiteral(" disabled /><br />\r\n\r\n                                    <input");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn btn-block\"");

WriteLiteral(" value=\"Desinscribirse\"");

WriteLiteral(" id=\"btnDesinscribir\"");

WriteLiteral(" ng-click=\"DesinscribirDemandante()\"");

WriteLiteral(" ");

WriteLiteral(" style=\"margin:auto; background-color: dimgray; color: white;\" />\r\n              " +
"                  </div>\r\n                            </div>\r\n                  " +
"      </div>\r\n                    </div>\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Atrás</button>\r\n                    </div>\r\n                </div>\r\n            " +
"</div>\r\n        </div>\r\n        <!-- ################################ -->\r\n     " +
"   <!--  MODAL EDITAR DATOS USUARIO  ###############################  -->\r\n     " +
"   <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalEditarUsuario\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalEditarUsuario\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important; margin-top:160px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color: #5bc0de; padding-bottom:0\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral("><p>Editar datos de usuario:</p></h4>\r\n                    </div>\r\n\r\n            " +
"        <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Nombre:</b><br />\r\n                    " +
"                <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarUsuario.Nombre\"");

WriteLiteral(" name=\"nombre\"");

WriteLiteral(" id=\"nombre\"");

WriteLiteral(" value=\"{{dataDemModel.Nombre}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Primer apellido:</b><br />\r\n           " +
"                         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarUsuario.Apellido1\"");

WriteLiteral(" name=\"apellido1\"");

WriteLiteral(" id=\"apellido1\"");

WriteLiteral(" value=\"{{dataDemModel.Apellido1}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Segundo apellido:</b><br />\r\n          " +
"                          <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarUsuario.Apellido2\"");

WriteLiteral(" name=\"apellido2\"");

WriteLiteral(" id=\"apellido2\"");

WriteLiteral(" value=\"{{dataDemModel.Apellido2}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                            <" +
"/div>\r\n\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Usuario:</b><br />\r\n                   " +
"                 <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarUsuario.Usuario\"");

WriteLiteral(" name=\"usuario\"");

WriteLiteral(" id=\"usuario\"");

WriteLiteral(" placeholder=\"{{dataDemModel.Usuario}}\"");

WriteLiteral(" disabled>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Contraseña:</b><br />\r\n                " +
"                    <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarUsuario.Contrasena\"");

WriteLiteral(" name=\"contrasena\"");

WriteLiteral(" id=\"contrasena\"");

WriteLiteral(" value=\"{{dataDemModel.Contrasena}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Tipo de usuario:</b><br />\r\n           " +
"                         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"tipoUsuario\"");

WriteLiteral(" id=\"tipoUsuario\"");

WriteLiteral(" placeholder=\"Demandante\"");

WriteLiteral(" disabled>\r\n                                </div>\r\n                            <" +
"/div>\r\n                        </div>\r\n                    </div>\r\n\r\n           " +
"         <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancelar</button>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" ng-click=\"ModificarDatosUsuario()\"");

WriteLiteral(@">Guardar datos</button>
                    </div>

                </div>
            </div>
        </div>
        <!-- ################################ -->
        <!--  MODAL EDITAR DATOS EMPLEADOR  ###############################  -->
        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalEditarDemandante\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalEditarDemandante\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important; margin-top:160px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color: #5bc0de; padding-bottom:0\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral("><p>Editar datos de empleador:</p></h4>\r\n                    </div>\r\n\r\n          " +
"          <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(">\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Experiencia laboral:</b><br />\r\n       " +
"                             <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarDemandante.ExperienciaLaboral\"");

WriteLiteral(" name=\"experienciaLaboral\"");

WriteLiteral(" id=\"experienciaLaboral\"");

WriteLiteral(" value=\"{{dataDemModel.ExperienciaLaboral}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Perfil de LinkedIn:</b><br />\r\n        " +
"                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarDemandante.PerfilLinkedin\"");

WriteLiteral(" name=\"perfilLinkedin\"");

WriteLiteral(" id=\"perfilLinkedin\"");

WriteLiteral(" value=\"{{dataDemModel.PerfilLinkedin}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Teléfono:</b><br />\r\n                  " +
"                  <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarDemandante.Telefono\"");

WriteLiteral(" name=\"telefono\"");

WriteLiteral(" id=\"telefono\"");

WriteLiteral(" value=\"{{dataDemModel.Telefono}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                            <" +
"/div>\r\n\r\n                            <div");

WriteLiteral(" class=\"col-sm-6\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Email:</b><br />\r\n                     " +
"               <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarDemandante.Email\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(" id=\"email\"");

WriteLiteral(" value=\"{{dataDemModel.Email}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n                             " +
"   <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Edad:</b><br />\r\n                      " +
"              <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarDemandante.Edad\"");

WriteLiteral(" name=\"edad\"");

WriteLiteral(" id=\"edad\"");

WriteLiteral(" value=\"{{dataDemModel.Edad}}\"");

WriteLiteral(" required>\r\n                                </div>\r\n\r\n                           " +
"     <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <b>Nivel de estudios:</b><br />\r\n         " +
"                           <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"dataDemModelEditarDemandante.NivelEstudios\"");

WriteLiteral(" ng-options=\"estudio.NivelEstudios as estudio.Nombre for estudio in estudios\"");

WriteLiteral(" required></select>\r\n                                </div>\r\n                    " +
"        </div>\r\n                        </div>\r\n                        <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                            <div");

WriteLiteral(" class=\"col-sm-12\"");

WriteLiteral(">\r\n                                <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                                    <br />\r\n                                  " +
"  <b>Foto de perfil:</b><br />\r\n                                    <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" fileread=\"dataDemModelEditarDemandante.ImagenB64\"");

WriteLiteral(" name=\"fotoPerfil\"");

WriteLiteral(" id=\"fotoPerfil\"");

WriteLiteral(" style=\"max-width:700px\"");

WriteLiteral(" required>\r\n                                </div>\r\n                            <" +
"/div>\r\n                        </div>\r\n                    </div>\r\n\r\n           " +
"         <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancelar</button>\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" ng-click=\"ModificarDatosDemandante()\"");

WriteLiteral(">Guardar datos</button>\r\n                    </div>\r\n\r\n                </div>\r\n  " +
"          </div>\r\n        </div>\r\n        <!-- ################################ " +
"-->\r\n\r\n    </div> \r\n</div>");

        }
    }
}
#pragma warning restore 1591
