#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Administracion;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Administracion/_Demandantes.cshtml")]
    public partial class _Views_Administracion__Demandantes_cshtml : System.Web.Mvc.WebViewPage<List<Core.Demandante.DemandanteModel>>
    {
        public _Views_Administracion__Demandantes_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Listado de demandantes:</h4><br />\r\n<div");

WriteLiteral(" data-ng-init=\"listDemandantes = ");

            
            #line 5 "..\..\Views\Administracion\_Demandantes.cshtml"
                                Write(Json.Encode(Model));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n\r\n\r\n\r\n    <form>\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(" style=\"border-radius:0\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></i></span>\r\n            <input");

WriteLiteral(" id=\"text\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"text\"");

WriteLiteral(" placeholder=\"Escribe para filtrar...\"");

WriteLiteral(" ng-model=\"filtroDemandantes\"");

WriteLiteral(" style=\"border-radius:0\"");

WriteLiteral(">\r\n        </div>\r\n    </form>\r\n\r\n    <br />\r\n\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n        <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n            <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'IdUsuario\')\"");

WriteLiteral(">\r\n                    Id Usuario \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'IdUsuario\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Id\')\"");

WriteLiteral(">\r\n                    Id Empleador \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Id\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Nombre\')\"");

WriteLiteral(">\r\n                    Nombre completo \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Nombre\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Edad\')\"");

WriteLiteral(">\r\n                    Edad \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Edad\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Email\')\"");

WriteLiteral(">\r\n                    Email \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Email\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'NivelEstudiosNombre\')\"");

WriteLiteral(">\r\n                    Nivel estudios \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'NivelEstudiosNombre\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'ExperienciaLaboral\')\"");

WriteLiteral(">\r\n                    Experiencia laboral \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'ExperienciaLaboral\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n            </tr>\r\n        </thead>\r\n\r\n        <" +
"tbody>\r\n            <tr");

WriteLiteral(" ng-repeat=\"x in listDemandantes | orderBy:sortKey:reverse | filter:filtroDemanda" +
"ntes\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.IdUsuario}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Id}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Nombre}} {{x.Apellido1}} {{x.Apellido2}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Edad}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Email}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NivelEstudiosNombre}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.ExperienciaLaboral}}</td>\r\n            </tr>\r\n        </tbody>\r\n    </table>" +
"\r\n</div>");

        }
    }
}
#pragma warning restore 1591
