#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Administracion;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Administracion/_Empleadores.cshtml")]
    public partial class _Views_Administracion__Empleadores_cshtml : System.Web.Mvc.WebViewPage<List<Core.Empleador.EmpleadorModel>>
    {
        public _Views_Administracion__Empleadores_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Listado de empleadores:</h4><br />\r\n<div");

WriteLiteral(" data-ng-init=\"listEmpleadores = ");

            
            #line 5 "..\..\Views\Administracion\_Empleadores.cshtml"
                                Write(Json.Encode(Model));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n        <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n            <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Id Usuario</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Id Empleador</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Nombre empresa</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Dirección</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Email</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Teléfono</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Nº Empleados</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">Tipo Industria</th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">&equiv;</th>\r\n            </tr>\r\n        </thead>\r\n\r\n        <tbody>\r\n          " +
"  <tr");

WriteLiteral(" ng-repeat=\"x in listEmpleadores\"");

WriteLiteral(">\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.IdUsuario}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Id}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NombreEmpresa}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Direccion}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Email}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Telefono}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NumeroEmpleados}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.TipoIndustriaNombre}}</td>\r\n                    <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-warning\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalEmpleadores(x.Id)\"");

WriteLiteral(">Ver detalles</button></td>\r\n                </tr>\r\n        </tbody>\r\n    </table" +
">\r\n</div>");

        }
    }
}
#pragma warning restore 1591
