#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Administracion;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Administracion/_Ofertas.cshtml")]
    public partial class _Views_Administracion__Ofertas_cshtml : System.Web.Mvc.WebViewPage<List<Core.Empleador.OfertaEmpleo>>
    {
        public _Views_Administracion__Ofertas_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Listado de ofertas:</h4><br />\r\n<div");

WriteLiteral(" data-ng-init=\"listOfertas = ");

            
            #line 5 "..\..\Views\Administracion\_Ofertas.cshtml"
                            Write(Json.Encode(Model));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n\r\n    ");

WriteLiteral("\r\n\r\n    <form>\r\n        <div");

WriteLiteral(" class=\"input-group\"");

WriteLiteral(">\r\n            <span");

WriteLiteral(" class=\"input-group-addon\"");

WriteLiteral(" style=\"border-radius:0\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-search\"");

WriteLiteral("></i></span>\r\n            <input");

WriteLiteral(" id=\"text\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"text\"");

WriteLiteral(" placeholder=\"Escribe para filtrar...\"");

WriteLiteral(" ng-model=\"filtroOfertas\"");

WriteLiteral(" style=\"border-radius:0\"");

WriteLiteral(">\r\n        </div>\r\n    </form>\r\n\r\n\r\n    <br />\r\n\r\n\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n        <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n            <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Id\')\"");

WriteLiteral(">\r\n                    Id Oferta\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Id\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'IdEmpleador\')\"");

WriteLiteral(">\r\n                    Id Empleador\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'IdEmpleador\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Titulo\')\"");

WriteLiteral(">\r\n                    Título\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Titulo\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'NumeroVacantes\')\"");

WriteLiteral(">\r\n                    Nº Vacantes\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'NumeroVacantes\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Sueldo\')\"");

WriteLiteral(">\r\n                    Sueldo\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Sueldo\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'FechaLanzamientoString\')\"");

WriteLiteral(">\r\n                    Fecha inicio\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'FechaLanzamientoString\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'FechaFinString\')\"");

WriteLiteral(">\r\n                    Fecha fin\r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'FechaFinString\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral("></th>\r\n            </tr>\r\n        </thead>\r\n\r\n        <tbody>\r\n            <tr");

WriteLiteral(" ng-repeat=\"x in listOfertas | orderBy:sortKey:reverse | filter:filtroOfertas\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Id}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.IdEmpleador}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Titulo}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.NumeroVacantes}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Sueldo}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaLanzamientoString}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.FechaFinString}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalOfertas(x.Id)\"");

WriteLiteral(" style=\"border-radius: 0\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-user\"");

WriteLiteral("></i></button></td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n</div>\r\n");

        }
    }
}
#pragma warning restore 1591
