#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Administracion;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Administracion/_Usuarios.cshtml")]
    public partial class _Views_Administracion__Usuarios_cshtml : System.Web.Mvc.WebViewPage<List<Core.Usuario.Usuario>>
    {
        public _Views_Administracion__Usuarios_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n<h4>Listado de usuarios:</h4>\r\n<div");

WriteLiteral(" data-ng-init=\"listUsuarios = ");

            
            #line 5 "..\..\Views\Administracion\_Usuarios.cshtml"
                             Write(Json.Encode(Model));

            
            #line default
            #line hidden
WriteLiteral("\"");

WriteLiteral(">\r\n\r\n\r\n    <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n        <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"filtro\"");

WriteLiteral(" class=\"form-control pull-right\"");

WriteLiteral(" placeholder=\"Escribe para filtrar...\"");

WriteLiteral(">\r\n        <br />\r\n    </div>\r\n\r\n    <br />\r\n\r\n    <table");

WriteLiteral(" class=\"table table-striped table-bordered\"");

WriteLiteral(" style=\"text-align:center\"");

WriteLiteral(">\r\n        <thead");

WriteLiteral(" style=\"background-color:#565656; overflow:hidden\"");

WriteLiteral(">\r\n            <tr");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Id\')\"");

WriteLiteral(">\r\n                    Id \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Id\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'User\')\"");

WriteLiteral(">\r\n                    Usuario \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'User\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Contrasena\')\"");

WriteLiteral(">\r\n                    Contraseña \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Contrasena\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'Nombre\')\"");

WriteLiteral(">\r\n                    Nombre completo \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'Nombre\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(" ng-click=\"sort(\'TipoUsuario\')\"");

WriteLiteral(">\r\n                    Tipo Usuario \r\n                    <span");

WriteLiteral(" class=\"glyphicon sort-icon\"");

WriteLiteral(" ng-show=\"sortKey==\'TipoUsuario\'\"");

WriteLiteral(" ng-class=\"{\'glyphicon-chevron-up\':reverse,\'glyphicon-chevron-down\':!reverse}\"");

WriteLiteral("></span>\r\n                </th>\r\n                <th");

WriteLiteral(" style=\"text-align:center; font-weight:normal; vertical-align:middle\"");

WriteLiteral(">&equiv;</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r\n            " +
"<tr");

WriteLiteral(" ng-repeat=\"x in listUsuarios | orderBy:sortKey:reverse | filter:filtro\"");

WriteLiteral(">\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Id}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.User}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Contrasena}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(">{{x.Nombre}} {{x.Apellido1}} {{x.Apellido2}}</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(" ng-if=\"x.TipoUsuario == 0\"");

WriteLiteral(">Empleador</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral(" ng-if=\"x.TipoUsuario == 1\"");

WriteLiteral(">Demandante</td>\r\n                <td");

WriteLiteral(" style=\"vertical-align:middle\"");

WriteLiteral("><button");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" data-toggle=\"modal\"");

WriteLiteral(" ng-click=\"ModalEliminarUsuario(x)\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-trash\"");

WriteLiteral("></i></button></td>\r\n            </tr>\r\n        </tbody>\r\n    </table>\r\n</div>\r\n\r" +
"\n<ar");

        }
    }
}
#pragma warning restore 1591
