#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Administracion;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Administracion/IndexAdministracion.cshtml")]
    public partial class _Views_Administracion_IndexAdministracion_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Views_Administracion_IndexAdministracion_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- Scripts-->\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_es" +
"-es.min.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 326), Tuple.Create("\"", 366)
, Tuple.Create(Tuple.Create("", 332), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 332), false)
, Tuple.Create(Tuple.Create(" ", 341), Tuple.Create("propios/scriptCompile.js", 342), true)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 386), Tuple.Create("\"", 437)
, Tuple.Create(Tuple.Create("", 392), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 392), false)
, Tuple.Create(Tuple.Create(" ", 401), Tuple.Create("propios/administracionController.js", 402), true)
);

WriteLiteral("></script>\r\n\r\n\r\n<div");

WriteLiteral(" ng-app=\"app\"");

WriteLiteral(">\r\n    <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(" ng-controller=\"AdministracionController\"");

WriteLiteral(" ng-init=\"GetAllOfertas()\"");

WriteLiteral(">\r\n\r\n\r\n        <br />\r\n        <div");

WriteLiteral(" class=\"col-sm-2\"");

WriteLiteral(">\r\n            <div>\r\n                ");

WriteLiteral("\r\n\r\n                <div");

WriteLiteral(" class=\"btn-group-vertical\"");

WriteLiteral(">\r\n                    <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"padding-right:90px; text-align:left\"");

WriteLiteral(" ng-click=\"GetAllOfertas()\"");

WriteLiteral(">");

WriteLiteral(" Ver ofertas</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"text-align:left\"");

WriteLiteral(" ng-click=\"GetDemandantes()\"");

WriteLiteral(">");

WriteLiteral(" Ver demandantes</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"text-align:left\"");

WriteLiteral(" ng-click=\"GetEmpleadores()\"");

WriteLiteral(">");

WriteLiteral(" Ver empleadores</button>\r\n                    <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" style=\"text-align:left\"");

WriteLiteral(" ng-click=\"GetUsuarios()\"");

WriteLiteral(">");

WriteLiteral(" Ver usuarios</button>\r\n                </div>\r\n\r\n            </div>\r\n        </d" +
"iv>\r\n\r\n        <div");

WriteLiteral(" class=\"col-sm-10 well well-lg\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" id=\"Ofertas\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"Demandantes\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"Empleadores\"");

WriteLiteral("></div>\r\n            <div");

WriteLiteral(" id=\"Usuarios\"");

WriteLiteral("></div>\r\n        </div>\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n\r\n        <!--  MODAL VER DETALLE MI OFERT" +
"A  ###############################  -->\r\n        <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalOfertasPorEmpleador\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important; width:1000px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color:#5bc0de; padding-bottom:10px\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Detalles del empleador:</h4>\r\n                    </div>\r\n                    <d" +
"iv");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n\r\n\r\n                        <div");

WriteLiteral(" id=\"OfertasPorEmpleador\"");

WriteLiteral("></div>\r\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Atrás</button>\r\n                    </div>\r\n                </div>\r\n            " +
"</div>\r\n        </div>\r\n        <!-- ################################ -->\r\n     " +
"   <!--  MODAL VER DETALLE MI OFERTA  ###############################  -->\r\n    " +
"    <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalDemandantesInscritos\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important; width:1000px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"text-align:center; background-color:#5bc0de; padding-bottom:10px\"");

WriteLiteral(">\r\n                        <h4");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white\"");

WriteLiteral(">Detalles de la oferta:</h4>\r\n                    </div>\r\n                    <di" +
"v");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n\r\n\r\n                        <div");

WriteLiteral(" id=\"DemandantesInscritos\"");

WriteLiteral("></div>\r\n\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Atrás</button>\r\n                    </div>\r\n                </div>\r\n            " +
"</div>\r\n        </div>\r\n        <!-- ################################ -->\r\n\r\n\r\n " +
"       <!--  MODAL ELIMINAR USUARIO  ###############################  -->\r\n     " +
"   <div");

WriteLiteral(" class=\"modal fade\"");

WriteLiteral(" id=\"modalEliminarUsuario\"");

WriteLiteral(" tabindex=\"-1\"");

WriteLiteral(" role=\"dialog\"");

WriteLiteral(" aria-labelledby=\"modalTitle\"");

WriteLiteral(" aria-hidden=\"true\"");

WriteLiteral(">\r\n            <div");

WriteLiteral(" class=\"modal-dialog\"");

WriteLiteral(" role=\"document\"");

WriteLiteral(" style=\"overflow-y: initial !important; padding-top:350px; width:450px\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"modal-content\"");

WriteLiteral(" style=\"overflow: hidden\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"modal-header\"");

WriteLiteral(" style=\"background-color:#565656; padding-bottom:0\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" class=\" modal-title\"");

WriteLiteral(" id=\"modalTitle\"");

WriteLiteral(" style=\"color:white; margin-bottom:10px\"");

WriteLiteral("><i");

WriteLiteral(" class=\"glyphicon glyphicon-trash\"");

WriteLiteral("></i></h5>\r\n                    </div>\r\n                    <div");

WriteLiteral(" class=\"modal-body\"");

WriteLiteral(" style=\"max-height: calc(100vh - 200px) !important; overflow-y: auto !important;\"" +
"");

WriteLiteral(">\r\n\r\n                        <p");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">¿Estás seguro de que deseas eliminar el usuario <span><b>{{usuarioParaEliminar.U" +
"ser}}</b></span>?</p>\r\n                        <p");

WriteLiteral(" style=\"text-align: center\"");

WriteLiteral(">El usuario se borrará permanentemente</p>\r\n                    </div>\r\n\r\n\r\n     " +
"               <div");

WriteLiteral(" class=\"modal-footer\"");

WriteLiteral(">\r\n                        <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"btn btn-\"");

WriteLiteral(" data-dismiss=\"modal\"");

WriteLiteral(">Cancelar</button>\r\n                        <button");

WriteLiteral(" class=\"btn btn-danger\"");

WriteLiteral(" ng-click=\"EliminarUsuario(usuarioParaEliminar.Id, usuarioParaEliminar.TipoUsuari" +
"o)\"");

WriteLiteral(">Eliminar</button>\r\n                    </div>\r\n                </div>\r\n         " +
"   </div>\r\n        </div>\r\n        <!-- ################################ -->\r\n\r\n" +
"\r\n\r\n\r\n    </div>\r\n    <br /><br /><br /><br />\r\n</div>");

        }
    }
}
#pragma warning restore 1591
