#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Optimization;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Empleador;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Empleador/PrimerAccesoEmpleador.cshtml")]
    public partial class _Views_Empleador_PrimerAccesoEmpleador_cshtml : System.Web.Mvc.WebViewPage<Core.Empleador.Empleador>
    {
        public _Views_Empleador_PrimerAccesoEmpleador_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<!-- Scripts-->\r\n<script");

WriteLiteral(" src=\"http://ajax.googleapis.com/ajax/libs/angularjs/1.3.10/angular.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"http://angular-ui.github.io/bootstrap/ui-bootstrap-tpls-0.13.0.min.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" src=\"https://cdnjs.cloudflare.com/ajax/libs/angular-i18n/1.5.0/angular-locale_es" +
"-es.min.js\"");

WriteLiteral("></script>\r\n\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 361), Tuple.Create("\"", 407)
, Tuple.Create(Tuple.Create("", 367), Tuple.Create<System.Object, System.Int32>(Href("~/Scripts")
, 367), false)
, Tuple.Create(Tuple.Create(" ", 376), Tuple.Create("propios/empleadorController.js", 377), true)
);

WriteLiteral("></script>\r\n\r\n<div");

WriteLiteral(" ng-app=\"app\"");

WriteLiteral(">\r\n    <img");

WriteAttribute("src", Tuple.Create(" src=\'", 450), Tuple.Create("\'", 491)
, Tuple.Create(Tuple.Create("", 456), Tuple.Create<System.Object, System.Int32>(Href("~/Imagenes/pexels-photo-884454.jpeg")
, 456), false)
);

WriteLiteral(" style=\'position:fixed;top:0;left:0;width:100%;height:100%;z-index:-1;opacity:0.2" +
"5\'");

WriteLiteral(">\r\n\r\n    \r\n    <div");

WriteLiteral(" ng-controller=\"EmpleadorController\"");

WriteLiteral(" data-ng-init=\"ObtenerIndustrias()\"");

WriteLiteral(" class=\"demo\"");

WriteLiteral(" style=\"width:auto\"");

WriteLiteral(">\r\n        <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral("></div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(">\r\n                    <div");

WriteLiteral(" class=\"titulo\"");

WriteLiteral(">\r\n                        <br>\r\n                        <h4");

WriteLiteral(" style=\"text-align:justify\"");

WriteLiteral(">Esta es la <b>primera vez que accedes</b>, por favor rellena los datos siguiente" +
"s para registrarte como nuevo <b>empleador</b>.</h4><br>\r\n                    </" +
"div>\r\n                </div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral("></div>\r\n            </div>\r\n\r\n            <div");

WriteLiteral(" class=\"row\"");

WriteLiteral(">\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral("></div>\r\n\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral(" style=\"height:680px\"");

WriteLiteral(">\r\n\r\n                    <div");

WriteLiteral(" class=\"well\"");

WriteLiteral(" style=\"border-radius:0; background-color:#383838; padding:0; margin:0; border:1p" +
"x solid #383838\"");

WriteLiteral(">\r\n                        <h5");

WriteLiteral(" style=\"text-align:center; color:white\"");

WriteLiteral(">Registro de nuevo empleador</h5>\r\n                    </div>\r\n                  " +
"  <div");

WriteLiteral(" class=\"well\"");

WriteLiteral(" style=\"border-radius:0; background-color:#f9f9f9;\"");

WriteLiteral(">\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Logo de la empresa</span> <i><small>(opciona" +
"l):</small></i><br />\r\n                            <input");

WriteLiteral(" type=\"file\"");

WriteLiteral(" fileread=\"emp.ImagenB64\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"logoEmpresa\"");

WriteLiteral(" id=\"logoEmpresa\"");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(" />\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Empresa:</span><br />\r\n                     " +
"       <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"emp.NombreEmpresa\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"nombreEmpresa\"");

WriteLiteral(" id=\"nombreEmpresa\"");

WriteLiteral(" ng-model=\"nombreEmpresa\"");

WriteLiteral(" required");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(">\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Dirección:</span><br />\r\n                   " +
"         <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"emp.Direccion\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"direccion\"");

WriteLiteral(" id=\"direccion\"");

WriteLiteral(" required");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(" />\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Teléfono</span> <i><small>(opcional):</small" +
"></i><br />\r\n                            <input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" ng-model=\"emp.Telefono\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"telefono\"");

WriteLiteral(" id=\"telefono\"");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(" />\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Email</span> <i><small>(opcional):</small></" +
"i><br />\r\n                            <input");

WriteLiteral(" type=\"email\"");

WriteLiteral(" ng-model=\"emp.Email\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"email\"");

WriteLiteral(" id=\"email\"");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(" />\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Número de empleados:</span><br />\r\n         " +
"                   <input");

WriteLiteral(" type=\"number\"");

WriteLiteral(" ng-model=\"emp.NumeroEmpleados\"");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" name=\"numeroEmpleados\"");

WriteLiteral(" id=\"numeroEmpleados\"");

WriteLiteral(" placeholder=\"Mínimo 1 empleado\"");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(" />\r\n                        </div>\r\n\r\n                        <div");

WriteLiteral(" class=\"form-group\"");

WriteLiteral(">\r\n                            <span>Tipo de industria:</span><br />\r\n           " +
"                 <select");

WriteLiteral(" class=\"form-control\"");

WriteLiteral(" ng-model=\"emp.TipoIndustria\"");

WriteLiteral(" ng-options=\"industria.TipoIndustria as industria.Nombre for industria in industr" +
"ias\"");

WriteLiteral(" required");

WriteLiteral(" style=\"border-radius:0; max-width:500px; border-color:#dedede;\"");

WriteLiteral(">\r\n                                <option");

WriteLiteral(" value=\"\"");

WriteLiteral(" selected disabled hidden>Selecciona uno de la lista</option>\r\n                  " +
"          </select>\r\n                        </div>\r\n\r\n                        <" +
"div");

WriteLiteral(" class=\"form-group text-center\"");

WriteLiteral(">\r\n                            <br /><br />\r\n                            <input");

WriteLiteral(" type=\"submit\"");

WriteLiteral(" class=\"btn btn-success\"");

WriteLiteral(" value=\" Registrar empleador\"");

WriteLiteral(" id=\"btn-submit\"");

WriteLiteral(" ng-click=\"GuardarDatosEmpleador()\"");

WriteLiteral(" style=\"border-radius:0; border:none; max-width:none;\"");

WriteLiteral(">\r\n                        </div>\r\n                    </div>\r\n                </" +
"div>\r\n                <div");

WriteLiteral(" class=\"col-sm-4\"");

WriteLiteral("></div>\r\n\r\n            </div>\r\n        </form>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
